### ISSUE TITLE
How to initialize new list?

### ISSUE THREAD

**Issue by ikhodov** [ngs-doo/TemplaterExamples#11]
I've attached 2 files - template and output. What is the right way to force numbers in each block to start with 1? I've set it in template, but despite this setting we're still getting continuous numeration through all the blocks. Version we're using is 3.2.1
[template.docx](https://github.com/ngs-doo/TemplaterExamples/files/4003017/template.docx)
[output.docx](https://github.com/ngs-doo/TemplaterExamples/files/4003018/output.docx)

**Comment by zapov** [comment]
A way to get what you want is to use a single multilevel list instead of multiple lists. That way second level will restart as you expect it to. You can tweak the visual layout of the list to look as you want it to, like I did in your template
[multilevel-list.docx](https://github.com/ngs-doo/TemplaterExamples/files/4004659/multilevel-list.docx)

**Comment by zapov** [comment]
Please reopen if there are still some issues.

**Comment by ikhodov** [comment]
[template.docx](https://github.com/ngs-doo/TemplaterExamples/files/4271377/template.docx)
[output.docx](https://github.com/ngs-doo/TemplaterExamples/files/4271378/output.docx)
Hello, thanks for response. It worked fine, but for some reason same solution doesn't work with attached template. I have tried multilevel list and separate tables, but every time I get similar output with continuous numeration (attached example).  Could you please explain in a bit more details how lists are being handled by templater, so I wouldn't bother you anymore with same question?
