### ISSUE TITLE
Problem with list numeration (similar to #11)

### ISSUE THREAD

**Issue by ikhodov** [ngs-doo/TemplaterExamples#13]
Hello, thanks for response to #11. It worked fine, but for some reason same solution doesn't work with attached template. I have tried multilevel list and separate tables, but every time I get similar output with continuous numeration (attached example). Could you please explain in a bit more details how lists are being handled by templater, so I wouldn't bother you anymore with same question?

[template.docx](https://github.com/ngs-doo/TemplaterExamples/files/4271390/template.docx)
[output.docx](https://github.com/ngs-doo/TemplaterExamples/files/4271391/output.docx)

**Comment by zapov** [comment]
Please also provide JSON which I can feed via https://github.com/ngs-doo/TemplaterExamples/releases/tag/v4.3.0

I suspect it's something due to new MS Office list styles, but it would be much easier to test it if you also provided the data for it.

**Comment by zapov** [comment]
I've looked over this problem and...

I've recreated JSON example so I can feed it to TemplaterJson: 

    {
      "Organizations":[
        {"Period":{"StartDate":{"Year":2020}},"User":{"FullName":"user 1"},"Sports":[
          {"Name":"Football", "ByType":{
            "10":{
              "Trainers":[
                {"FullName":"trainer 1","Groups":[
                  {"Members":[
                    {"Person":{"FullName":"member1","FormattedBirthday":"today 1","SchoolName":"school 1"}},
                    {"Person":{"FullName":"member2","FormattedBirthday":"today 2","SchoolName":"school 2"}}
                  ]}
                ]},
                {"FullName":"trainer 2","Groups":[
                  {"Members":[
                    {"Person":{"FullName":"member3","FormattedBirthday":"today 3","SchoolName":"school 3"}},
                    {"Person":{"FullName":"member4","FormattedBirthday":"today 4","SchoolName":"school 4"}},
                    {"Person":{"FullName":"member5","FormattedBirthday":"today 5","SchoolName":"school 5"}}
                  ]}
                ]}
              ]
            },
            "20-150":{
              "Trainers":[
                {"FullName":"trtp1","Types":[
                  {"Type":"type 3","FullName":"trainer 3","Groups":[
                    {"Members":[
                      {"Person":{"FullName":"member7","FormattedBirthday":"today 7","SchoolName":"school 7","Rank":{"Rank":1}}},
                      {"Person":{"FullName":"member8","FormattedBirthday":"today 8","SchoolName":"school 8","Rank":{"Rank":2}}}
                    ]}
                  ]},
                  {"Type":"type 4","FullName":"trainer 4","Groups":[
                    {"Members":[
                      {"Person":{"FullName":"member9","FormattedBirthday":"today 9","SchoolName":"school 9","Rank":{"Rank":3}}},
                      {"Person":{"FullName":"member10","FormattedBirthday":"today 10","SchoolName":"school 10","Rank":{"Rank":4}}},
                      {"Person":{"FullName":"member11","FormattedBirthday":"today 11","SchoolName":"school 11","Rank":{"Rank":5}}}
                    ]}
                  ]}
                ]}
              ]
            },
            "210-320":{
              "Trainers":[
                {"FullName":"trainer 5","Groups":[
                  {"Type":"type 5","Members":[
                    {"Person":{"FullName":"member17","FormattedBirthday":"today 17","SchoolName":"school 17","Rank":{"Rank":1}}},
                    {"Person":{"FullName":"member18","FormattedBirthday":"today 18","SchoolName":"school 18","Rank":{"Rank":2}}}
                  ]}
                ]},
                {"FullName":"trainer 6","Groups":[
                  {"Type":"type 6","Members":[
                    {"Person":{"FullName":"member19","FormattedBirthday":"today 19","SchoolName":"school 19","Rank":{"Rank":3}}},
                    {"Person":{"FullName":"member20","FormattedBirthday":"today 20","SchoolName":"school 20","Rank":{"Rank":4}}},
                    {"Person":{"FullName":"member21","FormattedBirthday":"today 21","SchoolName":"school 21","Rank":{"Rank":5}}}
                  ]}
                ]}
              ]
            }
          }}
        ]}
      ]
    }

In the future please provide such JSON so I don't need to do guess and try to come up with example data which might not fit the problem at hand.

I've changed the template so that it behaves as you expect it to (maybe): 
[list-template-hack.docx](https://github.com/ngs-doo/TemplaterExamples/files/4283753/list-template-hack.docx)

Currently Templater will invoke a new list number only when there is a tag on the list. So I added tags along the list number and used `:hide` metadata to remove those tags. It's kind of hacky solution but it does renumber the list as you expect it to (I've also changed the size of text to 1 so that template does not look really weird).

I've also looked into the expected behavior and concluded that Templater should be doing those renumbering out of the box in this cases (when there is nested table) so new version will behave like that without any changes: 
[list-new-version.docx](https://github.com/ngs-doo/TemplaterExamples/files/4283763/list-new-version.docx)

But there is something very interesting with your template which I'm not sure how to replicate. Your first and third lists have been setup in a way that they restart numbering on duplication, while the second list uses builtin style which does not restart numbering. How did you manage to setup template like that? Can you please explain the steps you used to set such style on the first list?

**Comment by zapov** [comment]
This should now work as expected in v4.4
