### ISSUE TITLE
Documentation or example: how to specify default format for dates, numbers, etc?

### ISSUE THREAD

**Issue by streamstr** [ngs-doo/TemplaterExamples#24]
Hello!
We are currently testing Templater, and I'm trying to find how to specify default formats of dates and numbers, so I don't need to write this: 
[[Statement.Date]:format(**dd.MM.yyyy**)]
for every DateTime field in template. 

I want to write this:
[[Statement.Date]:format **()**]
and somehow be able to specify default format once for all template. Is this possible?

Thanks.

**Comment by zapov** [comment]
Hi,

you have two basic options:
 * you can use low level API to convert all DateTime into such string, like in here: https://github.com/ngs-doo/TemplaterExamples/blob/master/Advanced/CsvStreaming/src/Program.cs#L29
 * you can introduce a plugin with shorter name, eg [[Statement.Date]:f] which would then use the expected format

Low level plugin is the closest to what you want, since you can still write format(something else) and return string which will avoid the processing in the low level plugin

**Comment by streamstr** [comment]
Thanks a lot!
