### ISSUE TITLE
Where complete reference on built-in formatters, processors, etc could be found?

### ISSUE THREAD

**Issue by streamstr** [ngs-doo/TemplaterExamples#26]
I've read User's manual and found no section describing full lis of built-in formatters,processors, etc. with description of their arguments and so on. Then I found README.txt file but it seems not complete and lacking of details. For example in Collapse example template I can see functions collapseIf and collapseNonEmpty, which are not described anywhere in manual or readme file.

**Comment by zapov** [comment]
Usually most of plugin will be user defined: https://github.com/ngs-doo/TemplaterExamples/blob/master/Intermediate/CollapseRegion/src/Program.cs#L54
And you can disable the built-in ones. Ver1 did not have the ability of custom plugins so there are various built-in, but since they are easy to write it's better to use custom ones which you can debug.

**Comment by streamstr** [comment]
> so there are various built-in,

But where I can read about what plugins are built-in?


> but since they are easy to write it's better to use custom ones which you can debug.

So you suggest your customers to write all necessary plugins by themselves? Even plugins like format or collapse, that are built-in?


> But yes, README is the only place where all of them are listed

It means that README file is out-of-date - I've mentioned some plugins (for example, collapseIf and collapseNonEmpty), that are not listed here

**Comment by zapov** [comment]
collapseIf and collapseNonEempty are not built in. They exist only in those examples since they are registered in those examples.

Other collapse built-in plugins are described in user manual at page 24 and in various examples here.

Some of the formatters are language/platform specifics but since they are so simple the only description which currently exists is in the README and in various examples. We could describe the others more... but I would rather convey the understanding of how they are build/used.... rather than try and explain the behavior of built-in ones in great detail.

I agree that they all should be listed in user manual and explained with a more than a single sentence, but this does not exist currently. We'll look into improving that in the future

**Comment by zapov** [comment]
New user manual explains all built-in plugins in more details: https://templater.info/user-manual
