### ISSUE TITLE
How to hide blocks of word document with collapse plugin?

### ISSUE THREAD

**Issue by streamstr** [ngs-doo/TemplaterExamples#27]
Hello. I've trying to figure out how collapse plugin works and how to achieve behavior that I want.

I've attached small program and template with questions. Can you please help me to understand how situations in template can be handled?
[TemplaterPlayground.zip](https://github.com/ngs-doo/TemplaterExamples/files/5230069/TemplaterPlayground.zip)

Many thanks.

**Comment by zapov** [comment]
You need to have sections/page breaks around the region which you want to remove. Templater will use them as indicators where to start and where to end.

You can view them in the outline view. Eg look at the example: https://github.com/ngs-doo/TemplaterExamples/blob/master/Intermediate/WordTables/template/Tables.docx
through View -> Outline and you will see continuous sections breaks which define affected region

**Comment by streamstr** [comment]
At first, did you look through example template, that I've attached in archive? There are several questions about how collapse works in different situations. Am I right, that you recommend to use section breaks in any of described situations?

I've tried to add section breaks, but it doesnt work like expected. This is what I expect:
![image](https://user-images.githubusercontent.com/9412086/93421587-6a585200-f8ba-11ea-86e3-9008ea141455.png)

All other text should be preserved, as I enclosed tag, that will be collapsed, in section.

But this is what I've got:
![image](https://user-images.githubusercontent.com/9412086/93421641-94117900-f8ba-11ea-8516-02a57f703a32.png)

Why all text was removed?

**Comment by zapov** [comment]
So there are several things going on at the same time which makes it super confusing. To simplify discussion I renamed some of your tags so they don't have the same name... as this results in different behavior: [TemplaterCollapse.docx](https://github.com/ngs-doo/TemplaterExamples/files/5236554/TemplaterCollapse.docx)

First of all, the main problem you were experiencing is that Templater uses some assumption about the context it will work on. When you repeat the same tag it expands the initial context to cover the other placeholder with the same name (thus I changed the template)

The other important aspect is that Templater does not consider paragraph as resizable region. You can read more about it in the user manual at page 42: https://templater.info/user-manual
There is relevant example which might provide additional insights: https://github.com/ngs-doo/TemplaterExamples/tree/master/Beginner/Paragraphs
Thus the suggestion of using sections to constrain the region affected by the operation (but then again without changing the tag name you are again working with the entire document)

Another relevant behavior is that Templater will refuse do do tag removal if that would empty the entire document. While it would not be incorrect if it does that... it would be a lot more confusing that the current behavior (does not mean we will not change it some time in the future). This is the main reason your original template behaves as it does, as your setup resulted in most resize(tags, 0) returning false

Now onto the lists... in my template I've changed both tags in list to Field3... but if you pass JSON {"EmptyStringField3":""} it will remove only the first tag. This is mostly due to behavior of the default collapse handler which does a single resize(tag, 0) and exits. In your case it should actually check if there is same tag still in the document and call resize(tag, 0) until there is not such tags anymore. For this purpose its better to introduce a new plugin (eg collapse-all) which would behave as you expect it to.

During processing Templater will ignore metadata which it doesn't know how to handle... thus collapseInversed will not actually do anything... it will behave as that metadata didn't even existed.

As for the last question... with all this insights it should be clear that if sections are introduced it will remove everything within the section.

**Comment by streamstr** [comment]
@zapov, thanks for detailed answer!


> When you repeat the same tag it expands the initial context to cover the other placeholder with the same name

So If I have property EmptyStringField in my object, and this property should be rendered in different parts of document (and should be hidden/visible alongside with different surrounding text in each occurrence) I have to duplicate property and it's data in object, making "fake" property for each occurrence of original property (EmptyStringField1, EmptyStringField2, and so on)?

Also, am I right that from Templater's perspective there is no context in lines of plain text? There must be any object like section, list, table, etc?

And some general question: is Templater designed to deal with complex documents (documents containing things like nested collapsible text regions, tables, etc)? We have our own legacy templating engine built on top of Word XML documents and direct WML generation, and now we are in search of some fresh, supported, rich and simple for end-users templating engine. Simplicity for end-users to edit templates is the most important requirement in our search. Our templates are complex. For example, we have xml tag called Option, which can wrap any region of document, rows of plain text, tables, lists - anything, and which defines some logical conditions (which are calculated during document generation) to determine - show or hide contents of Option tag. Example of conditions can be expressions like "Table1.Field1 > 0 AND Table2.Field2 = Table3.Field3". Option tags can be nested, which makes it possible to create really complex documents. Can Templater be suitable for such kind of templates? I'm worrying, that if we choose to go with Templater, than we will have to write a lot of code to implement things like conditions and other. Another point is that one time we can come to a situation, when some of required behavior cannot be implemented with Templater.

So, maybe there are some examples of templates involving functionality I've described, that you can share? Or I can pass you one of our templates, so you can better understand our needs and maybe suggest something? I understand, that we are not your customers yet, and now asking a lot of (maybe stupid) questions, but we can't make a decision to buy Templater and integrate it in our system if we are not fully shure that all features of current templating mechanism are implemented in Templater (or can be simply implemented by ourselves). 

Thanks.

**Comment by zapov** [comment]
You should be able to create really complex document with lots of nested logic.
It might require some learning curve and adaptation, but it should be doable and its our goal to improve Templater to support more use cases.

We do offer source code licensing so customers are able to inject some custom behavior which is not yet supported in Templater but should resolve their use case.

I suggest you send us an email with an example template and output and we'll see how we can make your use case work. Ideally provide a small app sending the data too, or preferably JSON input which we can feed into the template.

**Comment by streamstr** [comment]
Good to hear it!

I'll prepare a template, which demonstrates our templating engine abilities, also there will be resulting word document, and I'll try to construct some JSON data. Unfortunately, I can't prepare an working app - our templating engine is very old and tightly coulped into main application and can't be simply extracted.

Which email address I can use?

I'll try to prepare all things on next week (I have many high-priority tasks now, and this one is in "background" mode)

**Comment by zapov** [comment]
Use the one from the website: https://templater.info/

**Comment by streamstr** [comment]
@zapov , hello again. I've prepared all data and send email on address from site.

**Comment by zapov** [comment]
There is now example of how to do this via content control in https://github.com/ngs-doo/TemplaterExamples/tree/master/Beginner/Paragraphs
