### ISSUE TITLE
Hiding tag do not remove the new line if its true

### ISSUE THREAD

**Issue by waqasraz** [ngs-doo/TemplaterExamples#35]
When we use the collapse tag if computed as true the tag disappears but the newline space stays.

![image](https://user-images.githubusercontent.com/1761304/108033666-684f1680-7045-11eb-9f41-7ff8036a1d46.png)

currently it shows like this

![image](https://user-images.githubusercontent.com/1761304/108034726-fd064400-7046-11eb-96c6-697ce7b9e98d.png)

I want to remove the space. Because it's adding up.

**Comment by zapov** [comment]
Are you sure collapse metadata is getting invoked?
It will not work on the root of the document, but in that case due to your setup hide metadata will trigger and replace tag with empty string.

Its hard to tell without the actual template, but I assume you are missing some kind of collection object there, such as list (without a bullet) or something alike

**Comment by waqasraz** [comment]
I think I did not explain it will. It does replace with empty sting but what required is to remove the blank line after replace.

**Comment by zapov** [comment]
Put that tag in a list and choose None from the Bullet library.
Also, you most likely don't want `:hide` metadata in there, so remove it as its most likely causing confusion in your case

**Comment by zapov** [comment]
Hopefully you managed to resolve this issue.
If my suggestion did not work, please reopen and provide document example + relevant JSON
